services:
  db:
    container_name: app_db
    image: postgres:18.4
    env_file:
      - .env.container
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
          pids: 200
        reservations:
          memory: 512M
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    restart: unless-stopped
  #================================================
  backend:
    container_name: app_server
    build:
      context: .
      dockerfile: ./configs/docker/backend.dockerfile
    env_file:
      - .env.container
    depends_on:
      db:
        condition: service_healthy
        restart: true
    ports:
      - "${BACKEND_HTTP_PORT}:${BACKEND_HTTP_PORT}"
    environment:
      - CONTAINER=true
    healthcheck:
      test: [ "CMD-SHELL", "./backend-healthcheck.sh" ]
      interval: 10s
      timeout: 3s
      start_period: 5s
      retries: 3
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '3.0'
          pids: 6000
        reservations:
          memory: 2G
          cpus: '1.5'
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "5"
  #================================================
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_proxy
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    ports:
      - "8080:80"
    volumes:
      - ./configs/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./configs/.ssh/cloudflare:/etc/nginx/certs:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

volumes:
  pg_data: