### Check server health
GET {{api_host}}/health
Accept: application/json
Content-Type: application/json
Origin: http://localhost:3000

### Get OpenAPI specification
GET {{api_host}}/openapi
Accept: application/json

### Register a user
POST {{api_host}}/auth/register
Accept: application/json
Content-Type: application/json

{
  "username": "testtest",
  "email": "test@test.com",
  "password": "Testtest1!"
}

### Login user
POST {{api_host}}/auth/login
Accept: application/json
Content-Type: application/json
Origin: some

{
  "email": "test",
  "password": "test"
}

### Get data from protected route
GET {{api_host}}/protected
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiZDYyMjU0MDUtNzUzZS00ZTgwLWFiNzItNTFkNGUzZjUwYzAzIiwidXNlcm5hbWUiOiJ0ZXN0IiwiZXhwIjoxNzg0MjA5MzgyfQ.ag3SDwrttKF2oQ5IgE9tL1qGP8Go8afMaYKcxKAHg_M