name: Code validation
on:
  push:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    environment: ci-test
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: video_processing_app
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      BACKEND_JWT_SECRET: ${{ vars.BACKEND_JWT_SECRET }}
      BACKEND_CORS_ORIGINS: ${{ vars.BACKEND_CORS_ORIGINS }}
      CONTAINER: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup system dependencies
        uses: ./.github/actions/setup-system-deps
      - name: Setup Cargo
        uses: ./.github/actions/setup-cargo
      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs
      - name: Run Database Migrations
        run: cd modules/backend && cargo sqlx migrate run
      - name: Generate openapi client
        run: |
          make prepare-frontend
      - name: Validate code
        run: |
          make check
      - name: Validate linters
        run: |
          make format-check
      - name: Validate tests
        run: |
          make test