name: Code validation
on:
  push:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      SQLX_OFFLINE: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Setup Cargo
        uses: ./.github/actions/setup-cargo
      - name: Setup NodeJS
        uses: ./.github/actions/setup-nodejs
      - name: Generate openapi spec and client
        run: |
          make generate-openapi
          make prepare-frontend
      - name: Validate code
        run: |
          make check
      - name: Validate linters
        run: |
          make format-check
      - name: Validate unit tests
        run: |
          make test-ci