name: Server deploy
on:
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    name: Server deploy
    runs-on: ubuntu-latest
    environment: production
    env:
      CONTAINER: true
      BACKEND_CORS_ORIGINS: ${{ vars.BACKEND_CORS_ORIGINS }}
      BACKEND_DB_MAX_CONNECTIONS: ${{ vars.BACKEND_DB_MAX_CONNECTIONS }}
      BACKEND_HOST: ${{ vars.BACKEND_HOST }}
      BACKEND_HTTP_PORT: ${{ vars.BACKEND_HTTP_PORT }}
      BACKEND_JWT_SECRET: ${{ vars.BACKEND_JWT_SECRET }}
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      POSTGRES_DB: ${{ vars.POSTGRES_DB }}
      POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
      POSTGRES_PASSWORD: ${{ vars.POSTGRES_PASSWORD }}
      POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
      POSTGRES_USER: ${{ vars.POSTGRES_USER }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload Docker Compose File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          passphrase: ${{ secrets.HETZNER_PASSPHRASE }}
          source: "./docker-compose.prod.yml"
          target: "/root/server/"
      - name: Write env variables to file
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          passphrase: ${{ secrets.HETZNER_PASSPHRASE }}
          script: |
            touch /root/server/.env
            echo "BACKEND_CORS_ORIGINS=${{ vars.BACKEND_CORS_ORIGINS }}" >> /root/server/.env
            echo "BACKEND_DB_MAX_CONNECTIONS=${{ vars.BACKEND_DB_MAX_CONNECTIONS }}" >> /root/server/.env
            echo "BACKEND_HOST=${{ vars.BACKEND_HOST }}" >> /root/server/.env
            echo "BACKEND_HTTP_PORT=${{ vars.BACKEND_HTTP_PORT }}" >> /root/server/.env
            echo "BACKEND_JWT_SECRET=${{ vars.BACKEND_JWT_SECRET }}" >> /root/server/.env
            echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> /root/server/.env
            echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> /root/server/.env
            echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> /root/server/.env
            echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> /root/server/.env
            echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> /root/server/.env
            echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> /root/server/.env
      - name: Pull docker image and restart server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: root
          key: ${{ secrets.HETZNER_SSH_KEY }}
          passphrase: ${{ secrets.HETZNER_PASSPHRASE }}
          script: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            cd /root/server
            docker compose --file ./docker-compose.prod.yml pull
            docker compose --file ./docker-compose.prod.yml up -d --remove-orphans